<?php

$file = $_GET['type'] ?? 'default';

$startMemory = memory_get_usage();
$startTime = microtime(true);

//include '../vendor/autoload.php';
include '../commonbase.php';

$table = [];
$table[] = new \App\Table\AdditionalEmail();
$table[] = new \App\Table\AssistantLeader();
$table[] = new \App\Table\AuditTrail();
$table[] = new \App\Table\Banner();
$table[] = new \App\Table\BikeShop();
$table[] = new \App\Table\BikeShopArea();
$table[] = new \App\Table\Blog();
$table[] = new \App\Table\BlogItem();
$table[] = new \App\Table\BoardMember();
$table[] = new \App\Table\Calendar();
$table[] = new \App\Table\CartItem();
$table[] = new \App\Table\CueSheet();
$table[] = new \App\Table\CueSheetVersion();
$table[] = new \App\Table\Customer();
$table[] = new \App\Table\DiscountCode();
$table[] = new \App\Table\Event();
$table[] = new \App\Table\File();
$table[] = new \App\Table\FileFolder();
$table[] = new \App\Table\Forum();
$table[] = new \App\Table\ForumAttachment();
$table[] = new \App\Table\ForumMember();
$table[] = new \App\Table\ForumMessage();
$table[] = new \App\Table\GaEvent();
$table[] = new \App\Table\GaOption();
$table[] = new \App\Table\GaPriceDate();
$table[] = new \App\Table\GaRider();
$table[] = new \App\Table\GaRiderSelection();
$table[] = new \App\Table\GaSelection();
$table[] = new \App\Table\HeaderContent();
$table[] = new \App\Table\HttpRequest();
$table[] = new \App\Table\Incentive();
$table[] = new \App\Table\Invoice();
$table[] = new \App\Table\InvoiceItem();
$table[] = new \App\Table\Job();
$table[] = new \App\Table\JobEvent();
$table[] = new \App\Table\JobShift();
$table[] = new \App\Table\JournalItem();
$table[] = new \App\Table\MailAttachment();
$table[] = new \App\Table\MailItem();
$table[] = new \App\Table\MailPiece();
$table[] = new \App\Table\Member();
$table[] = new \App\Table\MemberCategory();
$table[] = new \App\Table\MemberNotice();
$table[] = new \App\Table\MemberOfMonth();
$table[] = new \App\Table\Membership();
$table[] = new \App\Table\Migration();
$table[] = new \App\Table\Newsletter();
$table[] = new \App\Table\OauthToken();
$table[] = new \App\Table\OauthUser();
$table[] = new \App\Table\Payment();
$table[] = new \App\Table\PaypalRefund();
$table[] = new \App\Table\Permission();
$table[] = new \App\Table\PermissionGroup();
$table[] = new \App\Table\Photo();
$table[] = new \App\Table\PhotoComment();
$table[] = new \App\Table\PhotoFolder();
$table[] = new \App\Table\PhotoTag();
$table[] = new \App\Table\PointHistory();
$table[] = new \App\Table\Poll();
$table[] = new \App\Table\PollAnswer();
$table[] = new \App\Table\PollResponse();
$table[] = new \App\Table\PublicPage();
$table[] = new \App\Table\Redirect();
$table[] = new \App\Table\Reservation();
$table[] = new \App\Table\ReservationPerson();
$table[] = new \App\Table\Ride();
$table[] = new \App\Table\RideComment();
$table[] = new \App\Table\RideIncentive();
$table[] = new \App\Table\RideSignup();
$table[] = new \App\Table\RWGPS();
$table[] = new \App\Table\RWGPSAlternate();
$table[] = new \App\Table\RWGPSComment();
$table[] = new \App\Table\RWGPSRating();
$table[] = new \App\Table\Setting();
$table[] = new \App\Table\SigninSheet();
$table[] = new \App\Table\SigninSheetRide();
$table[] = new \App\Table\Slide();
$table[] = new \App\Table\SlideShow();
$table[] = new \App\Table\StartLocation();
$table[] = new \App\Table\StoreItem();
$table[] = new \App\Table\StoreItemDetail();
$table[] = new \App\Table\StoreItemOption();
$table[] = new \App\Table\StoreOption();
$table[] = new \App\Table\StoreOrder();
$table[] = new \App\Table\StorePhoto();
$table[] = new \App\Table\Story();
$table[] = new \App\Table\SystemEmail();
$table[] = new \App\Table\UserPermission();
$table[] = new \App\Table\Video();
$table[] = new \App\Table\VideoType();
$table[] = new \App\Table\VolunteerJobShift();
$table[] = new \App\Table\VolunteerPoint();
$table[] = new \App\Table\VolunteerPoll();
$table[] = new \App\Table\VolunteerPollAnswer();
$table[] = new \App\Table\VolunteerPollResponse();
$table[] = new \App\Table\Ziptax();

$endTime = microtime(true);
$finalMemory = memory_get_usage();

$memoryUsed = $finalMemory - $startMemory;
$microSeconds = $endTime - $startTime;

echo "Composer autoload takes {$memoryUsed} bytes of memory<br>";
echo "and took {$microSeconds} to load<br>";

$csv = \fopen($file . 'Class.csv', 'a+');

\fputcsv($csv, [count($table), $memoryUsed, $microSeconds]);
